name: Machine Prep
description: Track setup tasks and required peripherals for a WoRC 2026 machine
title: "[Machine]: "
body:
  - type: textarea
    id: purpose
    attributes:
      label: Machine purpose
      description: What is this machine being brought for?
      placeholder: "Example: scoring, display, testing, adminI don', backup"
    validations:
      required: false
